version: '3'
services:
  api:
    container_name: 'rpi3-api'
    image: astaech/rpi3-i2c-mongo
    build: ./src
    volumes:
      - ./src:/app
    devices:
      - /dev/i2c-1
    depends_on:
      - 'mongo'
  mongo:
    container_name: 'rpi3-mongo'
    image: mangoraft/mongodb-arm
    volumes:
      - ./data:/data
    ports:
      - '27017:27017'
      - '28017:28017'
    environment:
      AUTH: 'no'
